var thicknessArray=[];var thicknessArrayTmp=[];$(document).ready(function(){formateBuildThicknessOptions();formateCheckFilter()});function formateBuildThicknessOptions(){thicknessArrayTmp=$(".StandardFormate .standardFormat .meta").map(function(){var thickness=parseFloat($(this).attr("data-thickness"));return(thickness!=0)?thickness:""});thicknessArrayTmp.sort(function(a,b){return a-b});thicknessArray=[...new Set(thicknessArrayTmp)];var thicknessArrayTmp2=thicknessArray.filter(function(val){return val!=null&&val!=""});if(thicknessArrayTmp2.length>1){$.each(thicknessArrayTmp2,function(index,value){if(value){$("#FormatFilter #FilterDicke").append("<option value='"+value+"'>"+value+"</option>")}})}else{$("#FormatFilter #FilterDicke").parents(".filterEl").remove()}}
function isEmptyOrSpaces(str){return str===null||str.match(/^ *$/)!==null}
function formateBuildTypeOptions(){itemArrayTmp=$(".StandardFormate .standardFormat .meta").map(function(){var grouparray=[{group:$(this).attr("data-gruppe"),groupval:$(this).attr("data-gruppeVal")}]
return $(this).attr("data-gruppeVal")});itemArray=[...new Set(itemArrayTmp)];if(itemArray.length>1){$.each(itemArray,function(index,value){$("#FormatFilter #FilterGruppe").append("<option value='"+value+"'>"+value+"</option>")})}else{$("#FormatFilter #FilterGruppe").parents(".filterEl").remove()}}
function formateCheckFilter(){var anzahlItems=$(".StandardFormate .standardFormat .meta").length;if($(".StandardFormate .standardFormat .meta[data-aqua='0']").length==anzahlItems||$(".StandardFormate .standardFormat .meta[data-aqua='1']").length==anzahlItems){$("#FormatFilter #FilterAqua").parents(".filterEl").remove()}
if($(".StandardFormate .standardFormat .meta[data-befahrbar='befahrbar']").length==anzahlItems||$(".StandardFormate .standardFormat .meta[data-befahrbar='nicht']").length==anzahlItems||$(".StandardFormate .standardFormat .meta[data-befahrbar='bedingt']").length==anzahlItems){$("#FormatFilter #FilterBefahrbar").parents(".filterEl").remove()}
if($("#FormatFilter .filterEl").length<=1){$("#FormatFilter").remove()}}
$("#FormatFilter").change(function(){$(".StandardFormate .standardFormat").show();if($(this).find(".aqua").is(":checked")){$(".StandardFormate .standardFormat .meta[data-aqua='0']").parent(".standardFormat").hide()}
if($(this).find(".befahrbar").is(":checked")){$(".StandardFormate .standardFormat .meta[data-befahrbar='nicht']").parent(".standardFormat").hide()}
if($("#FormatFilter #FilterDicke").length){var selectedThickness=$("#FormatFilter #FilterDicke option:selected").text();var selectedThicknessVal=$("#FormatFilter #FilterDicke option:selected").val();if(selectedThicknessVal!="0"){$(".StandardFormate .standardFormat .meta[data-thickness!='"+selectedThickness+"']").parent(".standardFormat").hide()}}
if($("#FormatFilter #FilterGruppe").length){var selectedGruppe=$("#FormatFilter #FilterGruppe option:selected").attr("data-gruppeval");var selectedGruppeVal=$("#FormatFilter #FilterGruppe option:selected").val();if(selectedGruppeVal!="0"){$(".StandardFormate .standardFormat .meta[data-gruppeval!='"+selectedGruppeVal+"']").parent(".standardFormat").hide()}}});const findDuplicates=(arr)=>{let sorted_arr=arr.slice().sort();let results=[];for(let i=0;i<sorted_arr.length-1;i++){if(sorted_arr[i+1]==sorted_arr[i]){results.push(sorted_arr[i])}}
return results};
