var $MenuButton=$("#MenuButton"),$MainMenu=$("#MainMenu");$(document).ready(function(){menuReplaceR();checkMenuSubsections()});$(window).resize(function(){setMenuHeight()});$MenuButton.click(function(){$MainMenu.toggleClass("visible");$MenuButton.toggleClass("icon-menu").toggleClass("icon-left-big");setMenuHeight()});var setMenuHeight=function(){if($('#MenuButton:visible').length){var winHig=$(window).height();$MainMenu.css({"max-height":winHig+"px"})}else{$MainMenu.css({"max-height":"auto"})}};var $HeaderWrapper=$("#HeaderWrapper");var $Header=$("#Header");$(document).scroll(function(){if($HeaderWrapper.length){var MENU_SMALLER_POSITION=110;var documentPosition=$(window).scrollTop();if(documentPosition>MENU_SMALLER_POSITION){$Header.addClass("fix");$("body").addClass("fixHeader")}else{$Header.removeClass("fix");$("body").removeClass("fixHeader")}}
if($("#MainMenu").length){var documentPosition=$(window).scrollTop();var mainTop=$("#Main").position().top;if(mainTop<documentPosition){$MenuButton.addClass("fix")}else{$MenuButton.removeClass("fix")}}});var menuReplaceR=function(){$(".checkR").each(function(){var value=$(this).html();value=value.replace(/<sup>®<\/sup>/g,"®");value=value.replace(/®/g,"<sup>®</sup>");$(this).html(value)})};var checkMenuSubsections=function(){var subsections={};var $subsectionElements={};$("#MainMenu").find(".menu_item.subsect").each(function(){var sectionTitle=$(this).attr("data-sub");var sectionHide=$(this).attr("data-sub-hide");var sectionNoGap=$(this).attr("data-no-gap");var $this=$(this);var gapClass="gap";if(sectionNoGap==="true"){gapClass=""}
if(sectionTitle.length){if(!subsections[sectionTitle]){subsections[sectionTitle]=[];$(this).replaceWith("<li class='menu_item menuSection "+gapClass+"'><span class='sectionTitle'>"+sectionTitle+" &gt;</span><ul id='CreatedMenuSection' class='subsection mainSubMenu' data-sub='"+sectionTitle+"'></ul></li>");$subsectionElements[sectionTitle]=$("#CreatedMenuSection");$("#CreatedMenuSection").removeAttr("id")}
$subsectionElements[sectionTitle].append($this)}
$(".subsection").hide();if(sectionHide!=="true"){$(".subsection .current").parents(".subsection").show().siblings(".sectionTitle").addClass("section")}})};$('body').on('click','.menuSection .sectionTitle',function(){$(this).toggleClass("open");$(this).siblings(".subsection").fadeToggle()});function initialShowAndHideSubmenu(){var winwid=$(window).width();if(winwid>=1900){relationMenuOpen()}
if(winwid>=1020&&$("body.ProductPage").length){relationMenuOpen();if(winwid<1900){relationMenuDelayedClose()}}}
$("#RelationMenuButton").click(function(){mainMenuClose();if($(this).hasClass("visible")){relationMenuClose()}else{relationMenuOpen()}});$("#MainMenuButton").click(function(){$("#RelationMenu").removeClass("show");$("#ProductFilterOverlay").removeClass("visible");if($(this).hasClass("visible")){mainMenuClose()}else{mainMenuOpen()}});function mainMenuClose(){$("#MainMenuWrapper").removeClass("show");$("#MainMenuButton").removeClass("visible")}
function mainMenuOpen(){$("#MainMenuWrapper").addClass("show");$("#MainMenuButton").addClass("visible")}
function relationMenuClose(){$("#RelationMenu").removeClass("show");$("#RelationMenuButton").removeClass("visible")}
function relationMenuOpen(){$("#RelationMenu").addClass("show");$("#RelationMenuButton").addClass("visible")}
function relationMenuDelayedClose(){setTimeout(function(){relationMenuClose()},1600)}
var $KatTitle=$("#RefKatList .refKatTitle");$KatTitle.click(function(){referenzToggleKatList()});$(document).ready(function(){if($(window).width()<1200){referenzToggleKatList()}});function referenzToggleKatList(){$KatTitle.toggleClass("visible");$(".refKatListe").slideToggle(200)};
