var overlays=[];var overlaysPlaces=[];var MIN_ACCURACY=2000;var mettenLatLng=[50.941093,7.299267];var map;var pageWithMap=!1;var mapTiles="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";var mapid="map";var directionsDisplay,directionsService;var routingControl=null;$(document).ready(function(){initialiseMap()});function initialiseMap(){if($("#"+mapid).length){map=L.map(mapid).setView([50.941093,7.299267],6);pageWithMap=!0;L.tileLayer(mapTiles,{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map)}}
$('#doGeoLocate').click(function(e){e.preventDefault();GeoErrorMessageClear();if(geoPosition.init()){geoPosition.getCurrentPosition(showPosition,error_callback,{enableHighAccuracy:!0,timeout:5000,maximumAge:0});if(directionsDisplay){clearDirections()}
clearPlaces()}
return!1});function error_callback(err){$("#ErrorMessage").html("Ihre Adresse konnte nicht ermittelt werden").addClass("active");setTimeout(GeoErrorMessageClear,3000)}
$("#ErrorMessage").click(function(){GeoErrorMessageClear()})
function GeoErrorMessageClear(){$("#ErrorMessage").html("").removeClass("active")}
function addMarker(latLng,options={}){return L.marker(latLng,options).addTo(map)}
function setPositionMarker(latitude,longitude,accuracy,content){clearOverlays();var circle=L.circle([latitude,longitude],{color:'rgb(117,174,244)',opacity:0.8,fillColor:'rgb(117,174,244)',fillOpacity:0.2,radius:accuracy}).addTo(map);var marker=L.marker([latitude,longitude]).addTo(map);overlays.push(marker);overlays.push(circle);map.fitBounds(circle.getBounds())}
function showPosition(p){var latitude=parseFloat(p.coords.latitude);var longitude=parseFloat(p.coords.longitude);var positionText="Position: "+latitude.toFixed(4)+", "+longitude.toFixed(4)+" Genauigkeit: "+p.coords.accuracy+"m";$("#AddressField").val(positionText);if(pageWithMap){map.flyTo(new L.LatLng(latitude,longitude),12);setPositionMarker(latitude,longitude,p.coords.accuracy,positionText)}
getReverseGeocodingData(latitude,longitude);if(p.coords.accuracy>MIN_ACCURACY){setPositioningInfo("Positionsbestimmung sehr ungenau ("+p.coords.accuracy/1000+"km)")}}
function getReverseGeocodingData(lat,lng){var latlng=L.latLng(lat,lng);var geocodeService=L.esri.Geocoding.geocodeService();geocodeService.reverse().latlng(latlng).run(function(error,result){if(error){return}
var address=result.address.Match_addr;$("#AddressField").val(address);if(pageWithMap){var markerAktuellePos=L.marker(result.latlng).addTo(map);markerAktuellePos.bindPopup(result.address.Match_addr);overlays.push(markerAktuellePos)}});return!1}
function setPositioningInfo(content){$("#pos").text(content)}
function clearOverlays(){while(overlays[0]){overlays.pop().remove()}}
function clearOverlayPlaces(){while(overlaysPlaces[0]){overlaysPlaces.pop().remove()}}
function clearDirections(){$("#DirectionsHL").empty();$("#mapsDirections").empty()}
function clearPlaces(){$(".addressSection").empty()}
$("#searchNearby").click(function(e){e.preventDefault();searchNearby()});$('#AddressField').keypress(function(event){if(event.which===13){event.preventDefault();searchNearby()}});function searchNearby(){if(directionsDisplay){clearDirections()}
clearPlaces();reverseGeolocationUndSuche()}
function reverseGeolocationUndSuche(){setPositioningInfo("");var $AddressField=$('#AddressField');var address=$AddressField.val();if(address.length>0){if(address.length<6){address="De "+address}
L.esri.Geocoding.geocode({requestParams:{maxLocations:1}}).text(address).run(function(err,results,response){if(err){console.log(err);return}
clearOverlays();const{lat,lng}=results.results[0].latlng;var latitude=lat;var longitude=lng;var positionText=results.results[0].text;$AddressField.val(positionText);$("#LatField").text(latitude);$("#LngField").text(longitude);if(pageWithMap){setPositionMarker(latitude,longitude,12,positionText)}
ajaxGetNearestPlaces()})}}
var imageDir="../images/";function ajaxGetNearestPlaces(){var address=$('#AddressField').val();var lat=$("#LatField").text();var lng=$("#LngField").text();var maxDistance=100000;var placeType=$('#PlacesType').attr("title");var href=$("#AdressWrapper").attr('data-href');var pagetype="HaendlerPage";cta=0;if($("body.ProductPage").length){pagetype="ProductPage";if($(".pdpConversionElemente").length){cta=1}}
var frage={"Lat":lat,"Lng":lng,"MaxDistance":maxDistance,"Type":placeType,"PageType":pagetype,"CTA":cta};href=href.replace(/\?.*/,"");if(href[href.length-1]!=="/"){href+="/"}
var url=href+'AJAXOrteInDerNaehe';$.get(url,frage).done(function(data){$('#NeueHaendler').empty().append(data);var latlngbounds=new L.latLngBounds();$('#NeueHaendler').show().append($("#HaendlerPageLinkWrap").html());if($('#NeueHaendler #HaendlerPageLink').length){var haendlerlink=$('#NeueHaendler #HaendlerPageLink').attr("href")+"?ort="+encodeURIComponent(address);$('#NeueHaendler #HaendlerPageLink').attr("href",haendlerlink)}
clearOverlayPlaces();var i=0;if(pageWithMap){$("#NeueHaendler .haendler").each(function(){i++;var lat=$(this).find(".Lat").attr("title");var lng=$(this).find(".Lng").attr("title");var pos=L.latLng(lat,lng);var placeType=""+$(this).data("type").replace("ae","ä");var fpp=$(this).data("fpp");var pinImage=imageDir+'marker-rot.png';if(placeType==="Niederlassung"){pinImage=imageDir+'marker-rot-voll.png'}else if(placeType==="Fachpartner"){if(fpp==1){pinImage=imageDir+'marker-lila.png'}else{pinImage=imageDir+'marker-blau.png'}}
var pinIcon=L.icon({iconUrl:pinImage,iconSize:[15,29],iconAnchor:[8,28],popupAnchor:[3,-30]});var marker=addMarker([lat,lng],{icon:pinIcon});var content="<span style='font-weight:bold;'>"+$(this).find(".Name").text()+"</span> <br> "+$(this).find(".Address").html();var id=$(this).attr("id");var popup=L.popup();popup.setContent("<p class='map_info_window' >"+content+"</p>");marker.bindPopup(popup);marker.on("click",function(){$('.place').removeClass("mark");$('html,body').animate({scrollTop:$("#"+id).addClass("mark").offset().top-20},'slow')});marker.on("mouseover",function(e){this.openPopup()});marker.on("mouseout",function(e){this.closePopup()});if(i<8){latlngbounds.extend(pos)}
var positionMarker=overlays[0];latlngbounds.extend(positionMarker.getLatLng());overlaysPlaces.push(marker)});map.fitBounds(latlngbounds)}})}
$("body").on("click",".loadFppExtraInfo .button",function(){var $el=$(this).parents(".loadFppExtraInfo");if($el.attr("data-loaded")=="1"){}else{var href=$("#AdressWrapper").attr('data-href');var id=$(this).parents(".haendler").attr("data-id");var frage={"ID":id};var url=href+'AJAXInfoFPP';$.get(url,frage).done(function(data){$el.attr("data-loaded","1");$el.find(".contentWrap .content").html(data)})}
$el.toggleClass("show");$el.find(".contentWrap").slideToggle(170)});$('.addressSection').on('click','.calcRoute',function(){var place=$(this).parents(".place");$('.place').removeClass("mark");place.addClass("mark");var latFrom=$("#LatField").text();var lngFrom=$("#LngField").text();var fromAddress=[latFrom,lngFrom];var showToAddress=place.find(".Name").text()+", "+place.find(".zipAndCity").text();$("#DirectionsHL").empty().html("Route: <span class='rot'>"+$('#AddressField').val()+"</span> nach <span class='rot'>"+showToAddress+"</span>");var lat=place.find(".Lat").attr("title");var lng=place.find(".Lng").attr("title");var toAddress=[lat,lng];calcRoute(fromAddress,toAddress)});function calcRoute(start,end){if(routingControl!=null){map.removeControl(routingControl);routingControl=null;var latlngbounds=new L.latLngBounds();latlngbounds.extend(L.latLng(start));latlngbounds.extend(L.latLng(end));map.fitBounds(latlngbounds)}
routingControl=L.Routing.control({waypoints:[L.latLng(start),L.latLng(end)],router:L.Routing.mapbox('pk.eyJ1Ijoicm95YWxwdWxwIiwiYSI6ImNrZWNsZjFjNDBqdWoycG1reDVsZDlrZGEifQ.BkViP-wUrtgVzmYzu2BxaA',{profile:'mapbox/driving-traffic',language:'de',alternatives:'true'}),routeWhileDragging:!0});routingControl._map=map;var controlDiv=routingControl.onAdd(map);document.getElementById('mapsDirections').appendChild(controlDiv);{}}
$(".clickfilter").click(function(){checkGeoFilter($(this));uncheckGeoFilter($(".clickfilter").not($(this)));var placeType=$(this).data("type");$("#PlacesType").attr("title",placeType);if(placeType==="HP"){$(".typeGroup,.mapsLocation").show()}else{$(".typeGroup,.mapsLocation").hide();$(".typeGroup."+placeType,".mapsLocation."+placeType).show()}
searchNearby()});var changeGeoFilter=function($el){$el.toggleClass("icon-check");$el.toggleClass("icon-check-empty")}
var checkGeoFilter=function($el){$el.addClass("icon-check");$el.removeClass("icon-check-empty")}
var uncheckGeoFilter=function($el){$el.removeClass("icon-check");$el.addClass("icon-check-empty")};