<? if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();?>

<?$APPLICATION->IncludeComponent(
    "bitrix:catalog.products.viewed",
    ".default",
    array(
        "ACTION_VARIABLE" => "action_cpv",
        "ADDITIONAL_PICT_PROP_2" => "MORE_PHOTO",
        "ADDITIONAL_PICT_PROP_3" => "-",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_TO_BASKET_ACTION" => "ADD",
        "BASKET_URL" => "/personal/cart/",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "3600",
        "CACHE_TYPE" => "A",
        "CART_PROPERTIES_2" => array(
            0 => "NEWPRODUCT",
            1 => "NEWPRODUCT,SALELEADER",
            2 => "",
        ),
        "CART_PROPERTIES_3" => array(
            0 => "COLOR_REF",
            1 => "SIZES_SHOES",
            2 => "",
        ),
        "CONVERT_CURRENCY" => "Y",
        "CURRENCY_ID" => "RUB",
        "DATA_LAYER_NAME" => "dataLayer",
        "DEPTH" => "",
        "DISCOUNT_PERCENT_POSITION" => "top-right",
        "ENLARGE_PRODUCT" => "STRICT",
        "ENLARGE_PROP_2" => "NEWPRODUCT",
        "HIDE_NOT_AVAILABLE" => "N",
        "HIDE_NOT_AVAILABLE_OFFERS" => "L",
        "IBLOCK_ID" => Indexis::getIblockId('catalog', 'catalog'),
        "IBLOCK_MODE" => "single",
        "IBLOCK_TYPE" => "catalog",
        "LABEL_PROP_2" => array(
            0 => "NEWPRODUCT",
        ),
        "LABEL_PROP_MOBILE_2" => "",
        "LABEL_PROP_POSITION" => "top-left",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "MESS_RELATIVE_QUANTITY_FEW" => "мало",
        "MESS_RELATIVE_QUANTITY_MANY" => "много",
        "MESS_SHOW_MAX_QUANTITY" => "Наличие",
        "OFFER_TREE_PROPS_3" => array(
            0 => "COLOR_REF",
            1 => "SIZES_SHOES",
            2 => "SIZES_CLOTHES",
        ),
        "PAGE_ELEMENT_COUNT" => "12",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(
            0 => "BASE",
        ),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_BLOCKS_ORDER" => "price,props,quantityLimit,sku,quantity,buttons,compare",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "",
        "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false},{'VARIANT':'3','BIG_DATA':false}]",
        "PRODUCT_SUBSCRIPTION" => "N",
        "PROPERTY_CODE_2" => array(
            0 => "NEWPRODUCT",
            1 => "SALELEADER",
            2 => "SPECIALOFFER",
            3 => "MANUFACTURER",
            4 => "MATERIAL",
            5 => "COLOR",
            6 => "SALELEADER,SPECIALOFFER,MATERIAL,COLOR,KEYWORDS,BRAND_REF",
            7 => "PRICE_HIDE",
        ),
        "PROPERTY_CODE_3" => array(
            0 => "ARTNUMBER",
            1 => "COLOR_REF",
            2 => "SIZES_SHOES",
            3 => "SIZES_CLOTHES",
            4 => "PRICE_HIDE",
        ),
        "PROPERTY_CODE_MOBILE_2" => "",
        "RELATIVE_QUANTITY_FACTOR" => "5",
        "SECTION_CODE" => "",
        "SECTION_ELEMENT_CODE" => "",
        "SECTION_ELEMENT_ID" => "",
        "SECTION_ID" => "",
        "SHOW_CLOSE_POPUP" => "N",
        "SHOW_DISCOUNT_PERCENT" => "Y",
        "SHOW_FROM_SECTION" => "N",
        "SHOW_MAX_QUANTITY" => "M",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_PRODUCTS_2" => "N",
        "SHOW_SLIDER" => "Y",
        "SLIDER_INTERVAL" => "3000",
        "SLIDER_PROGRESS" => "Y",
        "TEMPLATE_THEME" => "blue",
        "USE_ENHANCED_ECOMMERCE" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N",
        "COMPONENT_TEMPLATE" => ".default",
        "DISPLAY_COMPARE" => "N",
        "ADDITIONAL_PICT_PROP_7" => "-",
        "LABEL_PROP_7" => array(
            0 => "BESTSELLER",
        ),
        "ADDITIONAL_PICT_PROP_8" => "-",
        "LABEL_PROP_MOBILE_7" => array(
        )
    ),
    false
);?>