<?
define('CUSTOM_LAYOUT_PAGE', true);
define('PAGE_TYPE', 2);
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Контакты. Компания Стройсервис в Москве. ☎ +7 (495) 229-30-20");
$APPLICATION->SetPageProperty("PAGE_SECTION_CLASS", 'contacts');
$APPLICATION->SetPageProperty("MICROMARKING_PARAMS_PAGE_SECTION", 'itemscope itemtype="http://schema.org/LocalBusiness"');
?><? $APPLICATION->IncludeComponent(
    "bitrix:news.list",
    "contacts",
    array(
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "AJAX_MODE" => "N",
        "IBLOCK_TYPE" => "content",
        "IBLOCK_ID" => Indexis::getIblockId("contacts", "content"),
        "NEWS_COUNT" => "100",
        //"NEWS_COUNT" => "3",
        "SORT_BY1" => "SORT",
        "SORT_ORDER1" => "ASC",
        "SORT_BY2" => "ACTIVE_FROM",
        "SORT_ORDER2" => "DESC",
        "FILTER_NAME" => "certFilter",
        "FIELD_CODE" => array("ID", "NAME", "DETAIL_PICTURE"),
        "PROPERTY_CODE" => array('ADDRESS_1', 'ADDRESS_2', 'SCHEDULE', 'PHONE', 'EMAIL', 'MANAGER', 'MANAGER_PHOTO', 'PHONE_WHATSAPP', 'PHONE_PASS', 'NEED_ORDER_PASS', 'LATITUDE', 'LONGITUDE', 'HOW_TO_GET_CAR', 'HOW_TO_GET_PT', 'IMPORTANT_MESSAGE', 'ROAD_MAP'),
        "CHECK_DATES" => "Y",
        "DETAIL_URL" => "",
        "PREVIEW_TRUNCATE_LEN" => "",
        "ACTIVE_DATE_FORMAT" => "d F Y",
        "SET_TITLE" => "Y",
        "SET_BROWSER_TITLE" => "Y",
        "SET_META_KEYWORDS" => "Y",
        "SET_META_DESCRIPTION" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "ADD_SECTIONS_CHAIN" => "N",
        "HIDE_LINK_WHEN_NO_DETAIL" => "Y",
        "PARENT_SECTION" => "",
        "PARENT_SECTION_CODE" => "",
        "INCLUDE_SUBSECTIONS" => "Y",
        "CACHE_TYPE" => "A",
        "CACHE_TIME" => "360000",
        "CACHE_FILTER" => "Y",
        "CACHE_GROUPS" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "PAGER_TITLE" => "Сертификаты",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "stroyservis",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_BASE_LINK_ENABLE" => "Y",
        "SET_STATUS_404" => "N",
        "SHOW_404" => "N",
        "MESSAGE_404" => "",
        "PAGER_BASE_LINK" => "",
        "PAGER_PARAMS_NAME" => "",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
    )
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>