<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.section.list",
	"map",
	Array(
		"ADDITIONAL_COUNT_ELEMENTS_FILTER" => "additionalCountFilter",
		"ADD_SECTIONS_CHAIN" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COMPONENT_TEMPLATE" => "panel-grid",
		"COUNT_ELEMENTS" => "N",
		"COUNT_ELEMENTS_FILTER" => "CNT_ACTIVE",
		"FILTER_NAME" => "sectionsFilter",
		"HIDE_SECTIONS_WITH_ZERO_COUNT_ELEMENTS" => "N",
		"IBLOCK_ID" => WAREHOUSES_IB_ID,
		"IBLOCK_TYPE" => "info",
		"MAP_CENTER" => "[55.60256185712297, 37.38446735731921]",
		"MAP_ZOOM" => "10.85",
		"SECTION_CODE" => $_REQUEST["SECTION_CODE"],
		"SECTION_FIELDS" => array(0=>"ID",1=>"NAME",2=>"PICTURE",3=>"DETAIL_PICTURE",4=>"",),
		"SECTION_ID" => "",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"UF_STORE_ID",1=>"",),
		"SHOW_PARENT_NAME" => "Y",
		"TITLE" => "Адреса складов",
		"SECTION_CLASS" => $arParams['SECTION_CLASS'],
		"TOP_DEPTH" => "1",
		"VIEW_MODE" => "LINE"
	)
);?>