<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Наши услуги и сервисы");
?>

<? $APPLICATION->IncludeComponent("bitrix:news", "services", array(
    "IBLOCK_TYPE" => "content",
    "IBLOCK_ID" => "12",
    "NEWS_COUNT" => "30",
    "USE_SEARCH" => "N",
    "USE_RSS" => "N",
    "USE_RATING" => "N",
    "USE_CATEGORIES" => "N",
    "USE_FILTER" => "N",
    "SORT_BY1" => "ACTIVE_FROM",
    "SORT_ORDER1" => "DESC",
    "SORT_BY2" => "SORT",
    "SORT_ORDER2" => "ASC",
    "CHECK_DATES" => "Y",
    "SEF_MODE" => "Y",
    "SEF_FOLDER" => "/services/",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "AJAX_OPTION_HISTORY" => "N",
    "CACHE_TYPE" => "A",
    "CACHE_TIME" => "36000000",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "Y",
    "SET_TITLE" => "Y",
    "SET_STATUS_404" => "Y",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "ADD_SECTIONS_CHAIN" => "Y",
    "ADD_ELEMENT_CHAIN" => "Y",
    "USE_PERMISSIONS" => "N",
    "PREVIEW_TRUNCATE_LEN" => "",
    "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
    "LIST_FIELD_CODE" => array(
        "NAME",
        "PREVIEW_PICTURE",
    ),
    "LIST_PROPERTY_CODE" => array(
        "ICON",
        "CATEGORY",
        "LINK",
        "ADVANTAGES",
        "LIST",
        "LIST_TITLE",
        "BANNER",
    ),
    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
    "DISPLAY_NAME" => "N",
    "META_KEYWORDS" => "-",
    "META_DESCRIPTION" => "-",
    "BROWSER_TITLE" => "-",
    "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
    "DETAIL_FIELD_CODE" => array(
        "NAME",
        "PREVIEW_PICTURE",
        "DATE_CREATE"
    ),
    "DETAIL_PROPERTY_CODE" => array(
        "ICON",
        "CATEGORY",
        "LINK",
        "ADVANTAGES",
        "LIST",
        "LIST_TITLE",
        "BANNER",
        "DETAIL_TYPE",
        "GALLERY",
        "DOWNLOAD_FILE",
        "MODAL_FORM_TITLE",
        "MODAL_FORM_TITLE_HIGHLIGHT",
        "MODAL_FORM_DESCRIPTION",
        "MODAL_SUCCESS_DESCRIPTION",
        "MODAL_SUCCESS_TITLE",
        "MODAL_SUCCESS_TITLE_HIGHLIGHT",
        "MODAL_SUCCESS_BUTTON_TEXT",
        "MODAL_SUCCESS_BUTTON_LINK",
        "WEB_FORM_ID",
    ),
    "DETAIL_DISPLAY_TOP_PAGER" => "N",
    "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
    "DETAIL_PAGER_TITLE" => "Страница",
    "DETAIL_PAGER_TEMPLATE" => "",
    "DETAIL_PAGER_SHOW_ALL" => "Y",
    "PAGER_TEMPLATE" => ".default",
    "DISPLAY_TOP_PAGER" => "N",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "PAGER_TITLE" => "Новости",
    "PAGER_SHOW_ALWAYS" => "Y",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "Y",
    "DISPLAY_DATE" => "Y",
    "DISPLAY_PICTURE" => "Y",
    "DISPLAY_PREVIEW_TEXT" => "Y",
    "USE_SHARE" => "N",
    "SHOW_TAGS" => "Y",
    "AJAX_OPTION_ADDITIONAL" => "",
    "SEF_URL_TEMPLATES" => array(
        "news" => "index.php",
        "detail" => "#ELEMENT_CODE#/",
    )
),
    false
);?>

<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>