<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$request = \Bitrix\Main\Application::getInstance()->getContext()->getRequest();
$APPLICATION->SetTitle("Мероприятия");

$APPLICATION->IncludeComponent(
	"bitrix:news",
	"events_page",
	array(
		"IBLOCK_TYPE" => "news",
		"IBLOCK_ID" => "15",
		"NEWS_COUNT" => 15,
		"FILTER_NAME" => "",
		"USE_SEARCH" => "N",
		"USE_RSS" => "N",
		"USE_RATING" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER2" => "DESC",
		"CHECK_DATES" => "Y",
		"SEF_MODE" => "Y",
		"SEF_FOLDER" => "/our_events/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_SHADOW" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ADD_ELEMENT_CHAIN" => "Y",
		"USE_PERMISSIONS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "CODE",
			2 => "NAME",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_PICTURE",
			5 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "EVENT_TYPE",
			1 => "IS_OFFLINE",
			2 => "SPEAKERS",
			3 => "DETAIL_BUTTON_TEXT",
			4 => "DETAIL_BUTTON_LINK",
			5 => "",
			6 => "",
			7 => "",
			8 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"DISPLAY_NAME" => "N",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_PICTURE",
			3 => "DATE_CREATE",
			4 => "ID",
			5 => "CODE",
		),
		"DETAIL_PROPERTY_CODE" => array(
			0 => "GALLERY",
			1 => "VIDEO_YOUTUBE_LINK",
			2 => "VIDEO_IMAGE",
			3 => "PRIMARY_BUTTON_DISPLAY",
			4 => "PRIMARY_BUTTON_TEXT",
			5 => "PRIMARY_BUTTON_LINK",
			6 => "SECONDARY_BUTTON_TEXT",
			7 => "SECONDARY_BUTTON_DISPLAY",
			8 => "SECONDARY_BUTTON_LINK",
			9 => "",
		),
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"PAGER_TEMPLATE" => "events_load_more",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"SHOW_TAGS" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "news_page",
		"USE_REVIEW" => "N",
		"SET_LAST_MODIFIED" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"DETAIL_SET_CANONICAL_URL" => "N",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SEF_URL_TEMPLATES" => array(
			"news" => "index.php",
			"section" => "",
			"detail" => "news/#ELEMENT_CODE#/",
		),
		"SUBTITLE" => "Образовательные мероприятия как самостоятельно, так и совместно с нашими партнерами",
		"SHORT_DESCRIPTION" => "на крупных площадках <br>Москвы и онлайн",
		"NO_ITEMS_MESSAGE" => "На данный момент нет запланированных мероприятий"
	),
	false
);?>
<? require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>